### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by foopang** [andrecp/django-tutorial-docker-nginx-postgres#1]
Hi, n00b here. I just followed the tutorial but failed to run the project. Please can you help?

```
$ sh rebuild_docker.sh
postgres uses an image, skipping
Building django...
Step 0 : FROM python:2.7-onbuild
# Executing 3 build triggers
Trigger 0, COPY requirements.txt /usr/src/app/
Step 0 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Trigger 1, RUN pip install --no-cache-dir -r requirements.txt
Step 0 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
Trigger 2, COPY . /usr/src/app
Step 0 : COPY . /usr/src/app
 ---> Using cache
 ---> 69e2dca77370
Step 1 : ENV DJANGO_CONFIGURATION Docker
 ---> Using cache
 ---> 270fbc19c045
Step 2 : CMD gunicorn -c gunicorn_conf.py --chdir mysite mysite.wsgi:application --reload
 ---> Using cache
 ---> 625f575074fe
Successfully built 625f575074fe
Building nginx...
Step 0 : FROM nginx
 ---> 6886fb5a9b8d
Step 1 : MAINTAINER Andre Prado
 ---> Using cache
 ---> 4fe6f1f20017
Step 2 : COPY nginx.conf /etc/nginx/nginx.conf
 ---> Using cache
 ---> 2173090fed54
Successfully built 2173090fed54
Recreating djangotutorialdockernginxpostgres_postgres_1...
Recreating djangotutorialdockernginxpostgres_django_1...
Recreating djangotutorialdockernginxpostgres_nginx_1...
      Name             Command             State              Ports       
-------------------------------------------------------------------------
djangotutorialdo   gunicorn -c        Exit 1                              
ckernginxpostgre   gunicorn_conf.                                         
s_django_1         ...                                                    
djangotutorialdo   nginx -g daemon    Up                 443/tcp, 0.0.0.0 
ckernginxpostgre   off;                                  :80->80/tcp      
s_nginx_1                                                                 
djangotutorialdo   /docker-           Up                 5432/tcp         
ckernginxpostgre   entrypoint.sh                                          
s_postgres_1       postgres

$ docker-compose run django /bin/sh -c 'cd mysite;python manage.py migrate'
/bin/sh: 1: cd: can't cd to mysite
python: can't open file 'manage.py': [Errno 2] No such file or directory
```

**Comment by andrecp** [comment]
Hey, thanks for the interest!
Well that's odd, should work out of the box. What machine are you running this?

Can you run docker-compose run django /bin/sh -c 'ls /usr/src/app' and check if you have all the files there? The directory structure should mirror what you have in your host.

As you can see your container with the django app is not running, it has State: Exit 1.
Try to run docker-compose logs django and copy me the message also :)

Thanks

**Comment by foopang** [comment]
hi @andrecp, I am running it on a Macbook Pro OS X 10.10.4.

I get no output from `docker-compose run django /bin/sh -c 'ls /usr/src/app’`

Below is the output from `docker-compose logs django`

```
Attaching to djangotutorialdockernginxpostgres_django_1
django_1 | 
django_1 | Error: 'gunicorn_conf.py' doesn't exist
```

Thanks for checking this for me!

**Comment by andrecp** [comment]
So, basically, the problem is that Docker is not mapping your Django project files inside the django container.

Now I gotta tell you that I don't know why it wouldn't work... which branch / git commit are you in?
Which version of Docker and Docker-compose?

I am on Macbook Air OS X 10.10.4. So we have the same OS.

**Comment by foopang** [comment]
@andrecp Problem has been solved after I moved the project folder back to internal storage. Somehow it doesn’t work when I put the project folder to an external storage device. Thanks!

**Comment by andrecp** [comment]
Glad to hear! Check how docker volume work, might have something to do with it :)

Cheers
