### ISSUE TITLE
what tutorial were you following?

### ISSUE THREAD

**Issue by cyberbikepunk** [andrecp/django-tutorial-docker-nginx-postgres#2]
Hello,

Nice repo. Thanks for sharing. I want to learn docker in the context of django too. So I was curious. Did you follow the basic django tutorial or a more specific "django + docker" tutorial? It would be nice if you could add the link in the README.

Thanks,

Loic

**Comment by andrecp** [comment]
It was just the Django website tutorial and this link (is at the readme) http://docker.atbaker.me/

Thanks for the comment!
