### ISSUE TITLE
Staticfiles are not loaded

### ISSUE THREAD

**Issue by ghost** [andrecp/django-tutorial-docker-nginx-postgres#3]
Hey,

So I modified this project to work with my own Django app. I got it to work, except for the static files. All the requests end in a 403 error. Your project worked out of the box (including the static files) so it's probably my configuration that messed it up.

This is my folder structure:
  djangostack
  │   docker-compose.yml
  │   Dockerfile
  │   gunicorn_conf.py
  │   README.md
  │   rebuild_docker.sh
  │   requirements.txt
  │
  └───nginx
  │   │   Dockerfile
  │   │   nginx.conf
  │   │
  └───vms
      │   manage.py
      │
      ├───static (This is where the staticfiles are collected)
      │   └───admin
      │   └───website
      │  
      └───vms
      │   │   **init**.py
      │   │   settings.py
      │   │   urls.py
      │   │   wsgi.py
      │ 
      └───website
      │   └───static
      │   │   └───website
      │   │   │   └───css
      │   │   │   └───img
      │   │   │   └───js
      │   │ 
      │   └───templates
      │   │   └───website
      │   │ 
      │   │   admin.py
      │   │   forms.py
      │   │   **init**.py
      │   │   models.py
      │   │   tests.py
      │   │   views.py

This is my nginx.conf:

```
worker_processes 1;

events {

    worker_connections 1024;

}

http {

    server {
        listen 80;
        server_name example.org;

        access_log /dev/stdout;
        error_log /dev/stdout info;

        location /static {
            alias /usr/src/app/vms/static;
        }

        location / {
            proxy_pass http://django:8000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}
```

This is the static files section in my settings.py:
    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.8/howto/static-files/

```
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
```

**Comment by andrecp** [comment]
Hmm I will have a look and reply ! Do you have a git repo with your project?
Might be something with permission in the folders that nginx is serving static files from
